spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/secret_storage
    username: postgres
    password: 123
  data:
    redis:
      host:
        localhost
      port:
        6379
  jpa:
    hibernate:
      ddl-auto: validate

app:
  algorithm:
    hash:
      AES
    SHA:
      SHA-256
  token:
    expiration_time:
      86400000